name: Laravel

on:
  push:
    branches: [ "master", "develop"]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
    - name: Set up PHP
      uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'

    - name: Install Composer
      run: curl -sS https://getcomposer.org/installer | php

    - uses: actions/checkout@v4

    - name: Clear Composer cache
      run: composer clear-cache

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Check Database File
      run: ls -l database

    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
